[package]
name = "sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sample"
crate-type = ["cdylib"]


[dependencies]
rand = "0.8.5"
jni = "0.21.1"
num-traits = "0.2"
num-derive = "0.4"
num = "0.4"
rcommand = { git = "https://github.com/StemAcademyKids-Minecraft/rcommand.git", branch = "master"}

[dependencies.uuid]
version = "1.4.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]