use crate::command;
#[macro_export]
macro_rules! playsound {
    ($e:expr) => { $crate::playsound($e)};
    ($fmt:expr, $($arg:tt)*) => { $crate::playsound(format!($fmt, $($arg)*))};
}
pub fn playsound(comm: WORD) {
    match comm {
        WORD::Sword => command!("playsound minecraft:tango.sword master @a ~ ~ ~"),
        WORD::Acacia => command!("playsound minecraft:tango.acacia master @a ~ ~ ~"),
        WORD::Arrow => command!("playsound minecraft:tango.arrow master @a ~ ~ ~"),
        WORD::Axe => command!("playsound minecraft:tango.axe master @a ~ ~ ~"),
        WORD::Bed => command!("playsound minecraft:tango.bed master @a ~ ~ ~"),
        WORD::Birch => command!("playsound minecraft:tango.birch master @a ~ ~ ~"),
        WORD::Boat =>command!("playsound minecraft:tango.boat master @a ~ ~ ~"),
        WORD::Book =>command!("playsound minecraft:tango.book master @a ~ ~ ~"),
        WORD::Boots => command!("playsound minecraft:tango.boots master @a ~ ~ ~"),
        WORD::Bow => command!("playsound minecraft:tango.bow master @a ~ ~ ~"),
        WORD::Bucket => command!("playsound minecraft:tango.bucket master @a ~ ~ ~"),
        WORD::Charcoal => command!("playsound minecraft:tango.charcoal master @a ~ ~ ~"),
        WORD::Chest => command!("playsound minecraft:tango.chest master @a ~ ~ ~"),
        WORD::Chestplate =>command!("playsound minecraft:tango.chestplate master @a ~ ~ ~"),
        WORD::Clock => command!("playsound minecraft:tango.clock master @a ~ ~ ~"),
        WORD::Coal => command!("playsound minecraft:tango.coal master @a ~ ~ ~"),
        WORD::Cobblestone => command!("playsound minecraft:tango.cobblestone master @a ~ ~ ~"),
        WORD::Compass => command!("playsound minecraft:tango.compass master @a ~ ~ ~"),
        WORD::CopperBlock => command!("playsound minecraft:tango.copper_block master @a ~ ~ ~"),
        WORD::CopperIngot =>  command!("playsound minecraft:tango.copper_ingot master @a ~ ~ ~"),
        WORD::CopperOre => command!("playsound minecraft:tango.copper_ore master @a ~ ~ ~"),
        WORD::CraftingTable => command!("playsound minecraft:tango.crafting_table master @a ~ ~ ~"),
        WORD::DarkOak => command!("playsound minecraft:tango.dark_oak master @a ~ ~ ~"),
        WORD::Dirt => command!("playsound minecraft:tango.dirt master @a ~ ~ ~"),
        WORD::FishingRod => command!("playsound minecraft:tango.fishing_rod master @a ~ ~ ~"),
        WORD::Flint => command!("playsound minecraft:tango.flint master @a ~ ~ ~"),
        WORD::FlintAndSteel => command!("playsound minecraft:tango.flint_and_steel master @a ~ ~ ~"),
        WORD::Furnace => command!("playsound minecraft:tango.furnace master @a ~ ~ ~"),
        WORD::GoldBlock => command!("playsound minecraft:tango.gold_block master @a ~ ~ ~"),
        WORD::GoldIngot => command!("playsound minecraft:tango.gold_ingot master @a ~ ~ ~"),
        WORD::GoldOre => command!("playsound minecraft:tango.gold_ore master @a ~ ~ ~"),
        WORD::Helmet => command!("playsound minecraft:tango.helmet master @a ~ ~ ~"),
        WORD::Hoe => command!("playsound minecraft:tango.hoe master @a ~ ~ ~"),
        WORD::HorseArmor => command!("playsound minecraft:tango.horse_armor master @a ~ ~ ~"),
        WORD::IronBlock => command!("playsound minecraft:tango.iron_block master @a ~ ~ ~"),
        WORD::IronIngot => command!("playsound minecraft:tango.iron_ingot master @a ~ ~ ~"),
        WORD::IronOre => command!("playsound minecraft:tango.iron_ore master @a ~ ~ ~"),
        WORD::JungleTree => command!("playsound minecraft:tango.jungle_tree master @a ~ ~ ~"),
        WORD::Ladder => command!("playsound minecraft:tango.ladder master @a ~ ~ ~"),
        WORD::Lead => command!("playsound minecraft:tango.lead master @a ~ ~ ~"),
        WORD::Leggings => command!("playsound minecraft:tango.leggings master @a ~ ~ ~"),
        WORD::Mangrove =>  command!("playsound minecraft:tango.mangrove master @a ~ ~ ~"),
        WORD::Map => command!("playsound minecraft:tango.map master @a ~ ~ ~"),
        WORD::MusicDisc => command!("playsound minecraft:tango.music_disc master @a ~ ~ ~"),
        WORD::NameTag => command!("playsound minecraft:tango.name_tag master @a ~ ~ ~"),
        WORD::Paper => command!("playsound minecraft:tango.paper master @a ~ ~ ~"),
        WORD::Pickaxe => command!("playsound minecraft:tango.pickaxe master @a ~ ~ ~"),
        WORD::Plank => command!("playsound minecraft:tango.plank master @a ~ ~ ~"),
        WORD::RawCopper => command!("playsound minecraft:tango.raw_copper master @a ~ ~ ~"),
        WORD::RawGold => command!("playsound minecraft:tango.raw_gold master @a ~ ~ ~"),
        WORD::RawIron => command!("playsound minecraft:tango.raw_iron master @a ~ ~ ~"),
        WORD::Saddle => command!("playsound minecraft:tango.saddle master @a ~ ~ ~"),
        WORD::Sand => command!("playsound minecraft:tango.sand master @a ~ ~ ~"),
        WORD::Shears => command!("playsound minecraft:tango.shears master @a ~ ~ ~"),
        WORD::Shield => command!("playsound minecraft:tango.shield master @a ~ ~ ~"),
        WORD::Shovel => command!("playsound minecraft:tango.shovel master @a ~ ~ ~"),
        WORD::Spruce => command!("playsound minecraft:tango.spruce master @a ~ ~ ~"),
        WORD::Spyglass => command!("playsound minecraft:tango.spyglass master @a ~ ~ ~"),
        WORD::Stick => command!("playsound minecraft:tango.stick master @a ~ ~ ~"),
        WORD::Stone => command!("playsound minecraft:tango.stone master @a ~ ~ ~"),
        WORD::TotemOfUndying => command!("playsound minecraft:tango.totem_of_undying master @a ~ ~ ~"),
        WORD::Wood => command!("playsound minecraft:tango.wood master @a ~ ~ ~"),
        _=> {}
    }
}

#[derive(FromPrimitive,Clone, Copy)]
#[repr(usize)]
pub enum WORD {
    Sword,
    Axe,
    Pickaxe,
    Shovel,
    Bow,
    Arrow,
    FishingRod,
    Hoe,
    Bucket,
    Shears,
    Saddle,
    Lead,
    Boat,
    Paper,
    Book,
    Map,
    Compass,
    Clock,
    CraftingTable,
    Furnace,
    Chest,
    Bed,
    Coal,
    Charcoal,
    Flint,
    FlintAndSteel,
    Ladder,
    NameTag,
    Spyglass,
    MusicDisc,
    Helmet,
    Chestplate,
    Leggings,
    Boots,
    Shield,
    TotemOfUndying,
    HorseArmor,
    IronOre,
    RawIron,
    IronIngot,
    IronBlock,
    GoldOre,
    RawGold,
    GoldIngot,
    GoldBlock,
    CopperOre,
    RawCopper,
    CopperIngot,
    CopperBlock,
    Stone,
    Cobblestone,
    Sand,
    Dirt,
    Tree,
    Wood,
    Plank,
    Stick,
    Oak,
    Spruce,
    Birch,
    JungleTree,
    Acacia,
    DarkOak,
    Mangrove,
}
